### ISSUE TITLE
Group perms

### ISSUE THREAD

**Issue by redkk0523** [Tezk/LimitCrafting#1]
Hi good day, i like the idea of your plugin though im having a hard time trying to figure this out 

inside my limitcraft i have a group with a name of diamond.
in luck perms  i added limitcrafting.groups.diamond to a group 
that means that they cant craft items that i've stated inside config right ? 

when i tried it it didnt work 
![image](https://user-images.githubusercontent.com/92325343/138550130-396c1957-46c9-4d86-a57e-1f87c39c7513.png)
this is my setup 
![image](https://user-images.githubusercontent.com/92325343/138550140-421e2e00-e9a0-4171-957b-8c96b2afb841.png)

still not working i need help please

**Comment by tommicallef** [comment]
Looks fine to me. Can you please send me a pastebin of your entire limitcrafting config file? Is the console throwing any errors at all for limitcrafting? Are other features of the plugin working? Have you got the plugin itself enabled in the config? Make sure block-all-items is set to false if you want to only block specific items for specific groups. Also, I see you have an extra space in "enable-groups:  true", this might be causing a syntax error, I'm not too sure, so remove that space and see what happens. Also try making the items in the config all CAPS, so "NETHERITE_AXE" rather than "netherite_AXE".
