### ISSUE TITLE
It is not possible to give the right to craft an item to different groups.

### ISSUE THREAD

**Issue by desopher** [Tezk/LimitCrafting#2]
- For example, I want only the _**"doctor"**_ group to have access to brew rack crafting, and the regular player has no access to it. Yes, that works just fine! But, if there is a group of **_"potions chefs"_**, and I want them also have access to the brew rack crafting, then everything breaks. 

- **What it looks like in the config:**

```    
    potions_chefs: # limitcrafting.groups.potions_chefs
      - 'BREWING_STAND'
    doctor: # limitcrafting.groups.doctor
      - 'BREWING_STAND'
 ```

- If you have the same item in different groups, unfortunately that whole group (or both, I never figured it out) stops working. Is there any way to fix this?

**Comment by tommicallef** [comment]
It's been a while since I've worked with LimitCrafting/Minecraft, but from reading your message and reading over the default configuration file for LimitCrafting, I am pretty sure you are misunderstanding how the configuration works.

The groups section in config is not designed to allow those groups to craft items. It is designed to prohibit specific groups from crafting specific items. So from your existing config settings, both groups potions_chefs and doctor will not be able to craft a brewing stand. 

**The way in which you would achieve what you want to do is to do the following:**
Create a group called "regular" in LimitCrafting config groups section for your regular players, then add the BREWING_STAND to that. Then assign the permission limitcrafting.groups.regular to that group. Then have your regular players belong to the regular group. Then your regular players will not be able to craft the brewing stand. As long as your doctor and potion chefs groups do not have that permission, they will be allowed to craft the brewing stand, so long as BREWING_STAND is also not listed in the default-block-list.

It would look something like this:
```
## must be set to false as you want your doctor and potion chef groups to craft items
block-all-items: false
## this creates an empty default block list or you can add whatever items you do want to block for everyone
default-block-list: 
- 'AIR'

enable-groups: true
groups:
  regular:
  - 'BREWING_STAND'
```

Then have your regular players belong to group "regular" using a permissions/groups plugin. Group "regular" must then have the permission limitcrafting.groups.regular to inherit the LimitCrafting restriction from the config file.

Let me know how you go!
